### ISSUE TITLE
 LazyModel 7.0 fails with inheritance

### ISSUE THREAD

**Issue by tahitiangabriel** [wicketstuff/core#424]
Hi @svenmeier ,

I'm moving to wicket 7.0 and lazymodels are not working with classes using inheritance (it works fine without).

Here's my code : 
```Java
public static final LazyModel<String> CODe_DEVISE_MODEL = model(from(EnteteOperation.class).getCodeDevise());
```

And I'm getting the following error : 
```
Caused by: java.lang.IllegalArgumentException: null
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-4.2.jar:4.2]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-4.2.jar:4.2]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-4.2.jar:4.2]
	at net.sf.cglib.proxy.BridgeMethodResolver.resolveAll(BridgeMethodResolver.java:61) ~[cglib-3.1.jar:na]
	at net.sf.cglib.proxy.Enhancer.emitMethods(Enhancer.java:911) ~[cglib-3.1.jar:na]
	at net.sf.cglib.proxy.Enhancer.generateClass(Enhancer.java:498) ~[cglib-3.1.jar:na]
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25) ~[cglib-3.1.jar:na]
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216) ~[cglib-3.1.jar:na]
	at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:377) ~[cglib-3.1.jar:na]
	at net.sf.cglib.proxy.Enhancer.createClass(Enhancer.java:317) ~[cglib-3.1.jar:na]
	at org.wicketstuff.lazymodel.reflect.DefaultProxyFactory.createClass(DefaultProxyFactory.java:86) ~[wicketstuff-lazymodel-7.0.0.jar:7.0.0]
	at org.wicketstuff.lazymodel.reflect.CachingProxyFactory.createClass(CachingProxyFactory.java:38) ~[wicketstuff-lazymodel-7.0.0.jar:7.0.0]
	at org.wicketstuff.lazymodel.reflect.Evaluation.proxy(Evaluation.java:132) ~[wicketstuff-lazymodel-7.0.0.jar:7.0.0]
	at org.wicketstuff.lazymodel.LazyModel.from(LazyModel.java:555) ~[wicketstuff-lazymodel-7.0.0.jar:7.0.0]
```

I don't know if it's related to #257 

Edit : I'm using Java 8.

Regards

**Comment by svenmeier** [comment]
Please provide EnteteOperation's source or something similar so we can test this.

**Comment by tahitiangabriel** [comment]
@svenmeier 
With a quick-start it's working, so I have dig a little further and I have discover that I was having conflict versions with asm.
LazyModel is using 4.2 and wicket-ioc is using 5.0.3.
Is it possible to upgrade LazyModel dependency?

As a workaround I have put the following dependency in my pom.xml :
```
<dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm</artifactId>
      <version>5.0.3</version>
    </dependency>
```

**Comment by svenmeier** [comment]
I've aligned the dependencies in wicketstuff to the ones in wicket(-ioc).

Thanks.
