### ISSUE TITLE
Wicket rest annotaions - Ambiguous methods mapped for the current request

### ISSUE THREAD

**Issue by Thorben91** [wicketstuff/core#544]
Hey,
I am using version 7.4.0 of wicketstuff-restannotations and I get an exception for every call to a none existing method. So the overridable method "noSuitableMethodFound()" is never called and I can't implement an error handling of this case. Maybe the problem is, that the method "selectMostSuitedMethod()" accept a "highestScore" of "0".

**Code:**
`
List<ScoreMethodAndExtractPathVars> methodsWithScore = scoredMethods.get(highestScore);
if(methodsWithScore != null && methodsWithScore.size() > 1)
{
	// if we have more than one method with the highest score, throw
	// ambiguous exception.
	throwAmbiguousMethodsException(scoredMethods.getFirstValue(highestScore));
}
`

**Stacktrace:**
> org.apache.wicket.WicketRuntimeException: Ambiguous methods mapped for the current request: URL 'rest/callNotExistingMethod', HTTP method GET. Mapped methods: login
     at org.wicketstuff.rest.resource.AbstractRestResource.throwAmbiguousMethodsException(AbstractRestResource.java:499)
     at org.wicketstuff.rest.resource.AbstractRestResource.selectMostSuitedMethod(AbstractRestResource.java:472)
     at org.wicketstuff.rest.resource.AbstractRestResource.respond(AbstractRestResource.java:180)
     at org.apache.wicket.request.handler.resource.ResourceRequestHandler.respond(ResourceRequestHandler.java:105)
     at org.apache.wicket.request.handler.resource.ResourceReferenceRequestHandler.respond(ResourceReferenceRequestHandler.java:108)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
     at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
     at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
     at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
     at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)
     at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203)
     at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:284)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)
     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
     at org.eclipse.jetty.server.Server.handle(Server.java:518)
     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
     at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
     at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
     at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
     at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
     at java.lang.Thread.run(Unknown Source)

best regrads
Thorben

**Comment by bitstorm** [comment]
Done! thank you for opening this issue.

**Comment by Thorben91** [comment]
Thanks for the fast fix.
