### ISSUE TITLE
Select2 broken since migrating to open-json in wicket 6.27

### ISSUE THREAD

**Issue by lfultongt** [wicketstuff/core#613]
Viewing any page using the select2 component will produce the following exception:

org.apache.wicket.WicketRuntimeException: This call is not supported any longer, because of the change to open-json (https://github.com/tdunning/open-json) due to license issues. (See https://www.apache.org/legal/resolved#category-x)
     at org.apache.wicket.ajax.json.JSONWriter.<init>(JSONWriter.java:25)
     at org.wicketstuff.select2.json.JsonBuilder.<init>(JsonBuilder.java:44)
     at org.wicketstuff.select2.json.JsonBuilder.<init>(JsonBuilder.java:34)
     at org.wicketstuff.select2.Select2Choice.renderInitializationScript(Select2Choice.java:73)
     at org.wicketstuff.select2.AbstractSelect2Choice.renderHead(AbstractSelect2Choice.java:203)
     at org.wicketstuff.select2.Select2Choice.renderHead(Select2Choice.java:34)
     at org.apache.wicket.Component.renderHead(Component.java:4437)
     at org.apache.wicket.Component.renderHead(Component.java:2687)
     at org.apache.wicket.markup.renderStrategy.ChildFirstHeaderRenderStrategy$1.component(ChildFirstHeaderRenderStrategy.java:85)
     at org.apache.wicket.markup.renderStrategy.DeepChildFirstVisitor.visit(DeepChildFirstVisitor.java:96)
     at org.apache.wicket.markup.renderStrategy.DeepChildFirstVisitor.visit(DeepChildFirstVisitor.java:87)
     at org.apache.wicket.markup.renderStrategy.DeepChildFirstVisitor.visit(DeepChildFirstVisitor.java:87)
     at org.apache.wicket.markup.renderStrategy.DeepChildFirstVisitor.visit(DeepChildFirstVisitor.java:87)
     at org.apache.wicket.markup.renderStrategy.DeepChildFirstVisitor.visit(DeepChildFirstVisitor.java:51)
     at org.apache.wicket.markup.renderStrategy.ChildFirstHeaderRenderStrategy.renderChildHeaders(ChildFirstHeaderRenderStrategy.java:78)
     at org.apache.wicket.markup.renderStrategy.ChildFirstHeaderRenderStrategy.renderHeader(ChildFirstHeaderRenderStrategy.java:57)
     at org.apache.wicket.ajax.AbstractAjaxResponse.writeHeaderContribution(AbstractAjaxResponse.java:480)
     at org.apache.wicket.ajax.XmlAjaxResponse.writeComponent(XmlAjaxResponse.java:110)
     at org.apache.wicket.ajax.AbstractAjaxResponse.writeComponents(AbstractAjaxResponse.java:229)
     at org.apache.wicket.ajax.AbstractAjaxResponse.writeTo(AbstractAjaxResponse.java:154)
     at org.apache.wicket.ajax.AjaxRequestHandler.respond(AjaxRequestHandler.java:359)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:890)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:97)
     at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261)
     at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218)
     at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289)
     at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259)
     at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201)
     at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:282)
     at com.metalogic.metacat.web.wicket.common.servlet.filter.UserServletFilter.doFilter(UserServletFilter.java:54)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1495)
     at com.metalogic.metacat.web.wicket.common.servlet.filter.ServletPreferencesFilter.doFilter(ServletPreferencesFilter.java:25)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1487)
     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:427)
     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
     at org.eclipse.jetty.server.Server.handle(Server.java:370)
     at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
     at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:973)
     at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1035)
     at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:641)
     at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:231)
     at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
     at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
     at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
     at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
     at java.lang.Thread.run(Thread.java:745)

**Comment by solomax** [comment]
Was fixed with this commit https://github.com/wicketstuff/core/commit/d4dfe8946db5c6c6a21c1bd4383ba5f86ba5eb4e for 6.x
What version are you using?
What are your steps?

**Comment by solomax** [comment]
I can pack the release :)
Could you please check if latest SNAPSHOT works for you? (https://oss.sonatype.org/content/repositories/snapshots/org/wicketstuff/wicketstuff-select2/6.0-SNAPSHOT/)

**Comment by lfultongt** [comment]
It works.  Thanks!

**Comment by solomax** [comment]
Released, enjoy :)
