### ISSUE TITLE
wicketstuff-portlet and liferay 7

### ISSUE THREAD

**Issue by tahitiangabriel** [wicketstuff/core#614]
I 'm trying to use wicketstuff-portlet with liferay 7.
I know that liferay 7 is using OSGI modules now but legacy "wars" portlet are still working.

My wicket application do start but the homepage is never called. So I end up with an empty blank page.

Here's the log I get at debug level : 
```
DEBUG org.apache.wicket.portlet.WicketPortlet - Portlet "RENDER_PHASE" for wicket url:/wicket-test/
DEBUG o.a.wicket.protocol.http.servlet.ServletWebRequest - Calculating context relative path from: context path '/spring-portlet', filterPrefix 'wicket-test/', uri '/o/spring-portlet/wicket-test/'
DEBUG o.a.wicket.protocol.http.servlet.ServletWebRequest - Calculating context relative path from: context path '/spring-portlet', filterPrefix 'wicket-test/', uri '/o/spring-portlet/wicket-test/'
DEBUG o.a.wicket.protocol.http.servlet.ServletWebRequest - Calculating context relative path from: context path '/spring-portlet', filterPrefix 'wicket-test/', uri '/o/spring-portlet/wicket-test/'
DEBUG o.a.wicket.request.mapper.CompoundRequestMapper - No compatible mapper found for URL 't/?p_l_id=20146&p_v_l_s_g_id=0'
DEBUG o.a.wicket.protocol.http.servlet.ServletWebRequest - Calculating context relative path from: context path '/spring-portlet', filterPrefix 'wicket-test/', uri '/o/spring-portlet/wicket-test/'
DEBUG o.a.wicket.protocol.http.servlet.ServletWebRequest - Calculating context relative path from: context path '/spring-portlet', filterPrefix 'wicket-test/', uri '/o/spring-portlet/wicket-test/'
DEBUG org.apache.wicket.request.cycle.RequestCycle - No suitable handler found for URL t/?p_l_id=20146&p_v_l_s_g_id=0, falling back to container to process this request
DEBUG org.apache.wicket.portlet.WicketPortlet - ajax redirect url after inclusion:null
DEBUG org.apache.wicket.portlet.WicketPortlet - end of request, wicket url: /wicket-test/
```

Liferay seems to add 't/' in the URL that is not handle in the wicket-portlet bridge.

For testing purpose I've mounted the homepage on the "t" path just to see what shall happened (I know it's not the right way to solve this problem!). The page was then created and displayed correctly (Again, I know I'm not supposed to do that, it's was just for testing).

@kkaravitis have you ever tried using liferay 7?

**Comment by kkaravitis** [comment]
@tahitiangabriel Unfortunately I have never tried using liferay 7. I will check it and I hope to find a solution. Thank you very much for your testing against liferay 7 and feedback.

**Comment by kkaravitis** [comment]
@tahitiangabriel I managed to deploy the wicketstuff portlet examples (wicket version: 7.9.0) on liferay-ce-portal-7.0-ga3 and by testing some examples it seems that everything works ok.
The only problems I faced were regarding the deploy on liferay 7. I did not manage to install the wicket portlets examples via the application manager so I had to change the liferay relative files (e.g lliferay-plugin-package.properties) and the web.xml, build the war and put it into the tomcat deploy path.

Also I have to repeat that these wicket portlet examples seem to be functional inside the liferay 7 by using the apache wicket version 7 and not version 8.
The portlet bridge is not full functional for wicket version 8 and I hope to find time to fix its issues.

I attach the source code of liferay v7.0 and wicket v7.9.0 examples.
[wicketstuff-portlet-examples.zip](https://github.com/wicketstuff/core/files/1713610/wicketstuff-portlet-examples.zip)

**Comment by tahitiangabriel** [comment]
@kkaravitis 
Hello Konstantinos and thank you for your feedback.
I've used the code you provide and build it with "mvn packge -Pliferay"
Then I deployed it in the "deploy" directory of liferay.

Here's the errors I've got : 

```
20:49:37,026 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:252] Processing wicketstuff-portlet-examples-7.9.0.war
20:49:43,007 INFO  [fileinstall-C:/Users/gl/Downloads/liferay-ce-portal-7.0-ga4/osgi/war][BaseAutoDeployListener:43] Copying portlets for C:\Users\gl\Downloads\liferay-ce-portal-7.0-ga4\tomcat-8.0.32\temp\20180214204942970YWSAJEFN\wicketstuff-portlet-examples-7.9.0.war
20:49:43,108 INFO  [fileinstall-C:/Users/gl/Downloads/liferay-ce-portal-7.0-ga4/osgi/war][BaseDeployer:879] Deploying wicketstuff-portlet-examples-7.9.0.war
20:49:46,872 INFO  [fileinstall-C:/Users/gl/Downloads/liferay-ce-portal-7.0-ga4/osgi/war][BaseAutoDeployListener:50] Portlets for C:\Users\gl\Downloads\liferay-ce-portal-7.0-ga4\tomcat-8.0.32\temp\20180214204942970YWSAJEFN\wicketstuff-portlet-examples-7.9.0.war copied successfully
20:49:46,978 WARN  [fileinstall-C:/Users/gl/Downloads/liferay-ce-portal-7.0-ga4/osgi/war][WabProcessor:1022] The property "portal-dependency-jars" is deprecated. Specified JARs may not be included in the class path.
20:49:57,617 ERROR [fileinstall-C:/Users/gl/Downloads/liferay-ce-portal-7.0-ga4/osgi/war][com_liferay_portal_osgi_web_servlet_context_helper:97] Bundle wicketstuff-portlet-examples-7.9.0_7.4.0 [534] is unable to load filter org.apache.wicket.portlet.PortletFilter 
20:49:57,618 ERROR [fileinstall-C:/Users/gl/Downloads/liferay-ce-portal-7.0-ga4/osgi/war][com_liferay_portal_osgi_web_servlet_context_helper:97] Bundle wicketstuff-portlet-examples-7.9.0_7.4.0 [534] is unable to load filter org.apache.wicket.portlet.PortletFilter 
...
20:50:02,756 INFO  [fileinstall-C:/Users/gl/Downloads/liferay-ce-portal-7.0-ga4/osgi/war][HotDeployImpl:226] Deploying wicketstuff-portlet-examples-7.9.0 from queue
20:50:02,758 INFO  [fileinstall-C:/Users/gl/Downloads/liferay-ce-portal-7.0-ga4/osgi/war][PluginPackageUtil:1007] Reading plugin package for wicketstuff-portlet-examples-7.9.0
20:50:02,771 INFO  [fileinstall-C:/Users/gl/Downloads/liferay-ce-portal-7.0-ga4/osgi/war][PortletHotDeployListener:181] Registering portlets for wicketstuff-portlet-examples-7.9.0
20:50:04,739 INFO  [fileinstall-C:/Users/gl/Downloads/liferay-ce-portal-7.0-ga4/osgi/war][PortletHotDeployListener:298] 34 portlets for wicketstuff-portlet-examples-7.9.0 are available for use
20:50:05,622 INFO  [fileinstall-C:/Users/gl/Downloads/liferay-ce-portal-7.0-ga4/osgi/war][BundleStartStopLogger:35] STARTED wicketstuff-portlet-examples-7.9.0_7.4.0 [534]
```


The portlets do appear in the liferay "applications" menu. 
When I add one of them on a page, I then have the following error : 

```
20:53:30,875 ERROR [http-nio-8080-exec-9][JSONAction:98] com.liferay.portal.kernel.portlet.PortletContainerException: javax.servlet.ServletException: java.lang.StackOverflowError
20:53:30,998 ERROR [http-nio-8080-exec-9][status_jsp:903] com.liferay.portal.kernel.portlet.PortletContainerException: javax.servlet.ServletException: java.lang.StackOverflowError
20:53:31,022 ERROR [liferay/monitoring-1][ParallelDestination:55] Unable to process message {destinationName=liferay/monitoring, response=null, responseDestinationName=null, responseId=null, payload=[{displayName=WICKET 7 TREE PORTLET, portletId=wicket7treePortlet_WAR_wicketstuffportletexamples790_INSTANCE_ppkdqwNfGSyc, requestType=RENDER, {attributes=null, companyId=20116, groupId=20143, description=null, duration=0, name=wicket7treePortlet, namespace=com.liferay.monitoring.Portlet, requestStatus=null, stopWatch=0:00:00.182, timeout=0, user=30086}}, {displayName=Product Menu, portletId=com_liferay_product_navigation_product_menu_web_portlet_ProductMenuPortlet, requestType=RENDER, {attributes=null, companyId=20116, groupId=20143, description=null, duration=5, name=com_liferay_product_navigation_product_menu_web_portlet_ProductMenuPortlet, namespace=com.liferay.monitoring.Portlet, requestStatus=SUCCESS, stopWatch=0:00:00.005, timeout=0, user=30086}}, {displayName=User Personal Bar, portletId=com_liferay_product_navigation_user_personal_bar_web_portlet_ProductNavigationUserPersonalBarPortlet, requestType=RENDER, {attributes=null, companyId=20116, groupId=20143, description=null, duration=1, name=com_liferay_product_navigation_user_personal_bar_web_portlet_ProductNavigationUserPersonalBarPortlet, namespace=com.liferay.monitoring.Portlet, requestStatus=SUCCESS, stopWatch=0:00:00.001, timeout=0, user=30086}}, {displayName=Search, portletId=com_liferay_portal_search_web_portlet_SearchPortlet, requestType=RENDER, {attributes=null, companyId=20116, groupId=20143, description=null, duration=11, name=com_liferay_portal_search_web_portlet_SearchPortlet, namespace=com.liferay.monitoring.Portlet, requestStatus=SUCCESS, stopWatch=0:00:00.011, timeout=0, user=30086}}, {displayName=Navigation, portletId=com_liferay_site_navigation_menu_web_portlet_SiteNavigationMenuPortlet, requestType=RENDER, {attributes=null, companyId=20116, groupId=20143, description=null, duration=8, name=com_liferay_site_navigation_menu_web_portlet_SiteNavigationMenuPortlet, namespace=com.liferay.monitoring.Portlet, requestStatus=SUCCESS, stopWatch=0:00:00.008, timeout=0, user=30086}}, {referer=http://localhost:8080/, remoteAddr=127.0.0.1, requestURL=http://localhost:8080/c/portal/status.jsp_display, statusCode=500, userAgent=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.143 Safari/537.36 Vivaldi/1.95.1077.45, {attributes=null, companyId=20116, groupId=20143, description=Portal Request, duration=106, name=/c/portal/status, namespace=com.liferay.monitoring.Portal, requestStatus=SUCCESS, stopWatch=0:00:00.106, timeout=-1, user=30086}}, {referer=http://localhost:8080/, remoteAddr=127.0.0.1, requestURL=, statusCode=500, userAgent=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.143 Safari/537.36 Vivaldi/1.95.1077.45, {attributes=null, companyId=20116, groupId=20143, description=null, duration=129, name=/c/portal/status, namespace=com.liferay.monitoring.Portal, requestStatus=SUCCESS, stopWatch=0:00:00.129, timeout=-1, user=30086}}, {referer=http://localhost:8080/, remoteAddr=127.0.0.1, requestURL=, statusCode=500, userAgent=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.143 Safari/537.36 Vivaldi/1.95.1077.45, {attributes=null, companyId=20116, groupId=20143, description=null, duration=230, name=/c/portal/update_layout, namespace=com.liferay.monitoring.Portal, requestStatus=SUCCESS, stopWatch=0:00:00.230, timeout=-1, user=null}}], values={defaultLocale=fr_FR, companyId=20116, groupId=0, principalName=30086, permissionChecker=com.liferay.portal.kernel.util.TransientValue@519e19d4, siteDefaultLocale=fr_FR, themeDisplayLocale=fr_FR}}
com.liferay.portal.kernel.messaging.MessageListenerException: java.lang.NullPointerException
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:32)
	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
	at com.liferay.portal.kernel.messaging.ParallelDestination$1.run(ParallelDestination.java:52)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:756)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:667)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.liferay.portal.monitoring.internal.statistics.portlet.PortletStatistics.processDataSample(PortletStatistics.java:106)
	at com.liferay.portal.monitoring.internal.statistics.portlet.CompanyStatistics.processDataSample(CompanyStatistics.java:209)
	at com.liferay.portal.monitoring.internal.statistics.portlet.ServerStatistics.processDataSample(ServerStatistics.java:117)
	at com.liferay.portal.monitoring.internal.statistics.portlet.ServerStatistics.processDataSample(ServerStatistics.java:35)
	at com.liferay.portal.monitoring.internal.messaging.MonitoringMessageListener.processDataSample(MonitoringMessageListener.java:93)
	at com.liferay.portal.monitoring.internal.messaging.MonitoringMessageListener.doReceive(MonitoringMessageListener.java:120)
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:26)
	... 5 more
```

What exactly did you change in the liferay-plugin-package.properties and the web.xml files?

I'm using "liferay-ce-portal-7.0-ga4" with wicket 7.

**Comment by kkaravitis** [comment]
Hello Gabriel,
I receive the same error when I deploy the war in the "deploy" directory of liferay. It seems that something is going wrong when liferay tries to deploy the wicket portlets as a war osgi module.
But when I hot deploy the war into the webapps folder of tomcat, the portlets work.

Regarding the changes on the liferay-plugin-package.properties file I set the liferay version equal with 7.0.0

`liferay-versions=7.0.0+`

In the web.xml file I commented out the com.liferay.portal.kernel.servlet.PortletServlet servlet which the liferay needs in order to recognize the wicket portlets.

**Comment by tahitiangabriel** [comment]
@kkaravitis
Konstantinos,
Indeed it works if I deploy the war file directly in the tomcat/webapps directory.
Unfortunately some of the portlets (or demos) do not work (like the clock in the "AJAX BUILTIN PORTLET" or the file upload). I will need to investigate a little bit more on that.
I will start a new liferay project in a couple of month so I need to be sure that everything works smoothly.

**Comment by kkaravitis** [comment]
@tahitiangabriel 
Hello Gabriel,
Unfortunately I have not yet managed to thoroughly investigate the problems of apache wicket 7 portlets inside the liferay 7 portlet container. I hope that until the end of this week I will have done some progress and let you know.

**Comment by tahitiangabriel** [comment]
@kkaravitis 
Everything seems to work flawlessly when I deploy the war in the tomcat/webapps directory.
Unfortunately this is not very easy to develop an app if I need to build a war and deploy it every time I change a single line of code. It is very much time consuming.

Now I'm trying to make it work the right way with the liferay IDE in eclipse.
I've build this very simple wicket project in eclipse.
[wicket-portlet.zip](https://github.com/wicketstuff/core/files/1813074/wicket-portlet.zip).
The war do deploy without any problem and the wicket app starts correctly.
But when the portlet is used, the homepage is never called.
There seems to have something wrong with the request path.

```
2018-03-14 21:07:10.061 [http-nio-8080-exec-4] DEBUG org.apache.wicket.portlet.WicketPortlet - Portlet "RENDER_PHASE" for wicket url:/wicket-portlet/
2018-03-14 21:07:10.064 [http-nio-8080-exec-4] DEBUG o.a.wicket.protocol.http.servlet.ServletWebRequest - Calculating context relative path from: context path '/wicket-portlet', filterPrefix 'wicket-portlet/', uri '/o/wicket-portlet/wicket-portlet/'
2018-03-14 21:07:10.066 [http-nio-8080-exec-4] DEBUG o.a.wicket.protocol.http.servlet.ServletWebRequest - Calculating context relative path from: context path '/wicket-portlet', filterPrefix 'wicket-portlet/', uri '/o/wicket-portlet/wicket-portlet/'
2018-03-14 21:07:10.066 [http-nio-8080-exec-4] DEBUG o.a.wicket.protocol.http.servlet.ServletWebRequest - Calculating context relative path from: context path '/wicket-portlet', filterPrefix 'wicket-portlet/', uri '/o/wicket-portlet/wicket-portlet/'
2018-03-14 21:07:10.066 [http-nio-8080-exec-4] DEBUG o.a.wicket.request.mapper.CompoundRequestMapper - No compatible mapper found for URL 't/?p_l_id=20146&p_v_l_s_g_id=0'
2018-03-14 21:07:10.067 [http-nio-8080-exec-4] DEBUG o.a.wicket.protocol.http.servlet.ServletWebRequest - Calculating context relative path from: context path '/wicket-portlet', filterPrefix 'wicket-portlet/', uri '/o/wicket-portlet/wicket-portlet/'
2018-03-14 21:07:10.067 [http-nio-8080-exec-4] DEBUG o.a.wicket.protocol.http.servlet.ServletWebRequest - Calculating context relative path from: context path '/wicket-portlet', filterPrefix 'wicket-portlet/', uri '/o/wicket-portlet/wicket-portlet/'
2018-03-14 21:07:10.067 [http-nio-8080-exec-4] DEBUG org.apache.wicket.request.cycle.RequestCycle - No suitable handler found for URL t/?p_l_id=20146&p_v_l_s_g_id=0, falling back to container to process this request
2018-03-14 21:07:10.070 [http-nio-8080-exec-4] DEBUG org.apache.wicket.portlet.WicketPortlet - ajax redirect url after inclusion:null
2018-03-14 21:07:10.070 [http-nio-8080-exec-4] DEBUG org.apache.wicket.portlet.WicketPortlet - end of request, wicket url: /wicket-portlet/
```

My company is ready to pay anyone who can resolve this issue and can make wicket 7 works with liferay 7 (in war mode or osgi mode).
I will post an announcement about it on the wicket forum in a couple of days if you are interested in solving this.

Regards,
Gabriel.

**Comment by kkaravitis** [comment]
@tahitiangabriel 
Hello Gabriel, 
I changed the build.gradle and xml files in WEB-INF and I figured out to make the portlet to work. Please try this
[wicket-portlet.zip](https://github.com/wicketstuff/core/files/1817405/wicket-portlet.zip)

Here is a screenshot of liferay with your portlet
![screenshot from 2018-03-16 01-22-52](https://user-images.githubusercontent.com/16665277/37496008-c8e37608-28b8-11e8-9d49-d08320c9ef4a.png)

_Unfortunately this is not very easy to develop an app if I need to build a war and deploy it every time I change a single line of code. It is very much time consuming._

By using eclipse IDE you can develop and test a wicket 7 portlet without the need for deploying it as a war and putting into the webapps folder by hand. Also I do not use the liferay IDE.
First of all you have to add a tomcat 8 server to eclipse servers view, the tomcat 8 server that is included into the liferay.
Please see the screenshot below:
![screenshot from 2018-03-16 01-12-16](https://user-images.githubusercontent.com/16665277/37496216-df590ba4-28b9-11e8-9671-9bcf617ae83f.png)

**Comment by kkaravitis** [comment]
@tahitiangabriel
Also as you can see in the eclipse screenshot, you have to make the following tomcat configurations:
- Select the radio _Use tomcat installation_ 
- The deploy path must be the webapp folder of tomcat.

**Comment by tahitiangabriel** [comment]
@kkaravitis Thank you so much for your help.
It is working this way.

**Comment by kkaravitis** [comment]
@tahitiangabriel You are welcome.
