### ISSUE TITLE
inmethod grid 8.0.0-M9 is broken with wicket 8.0.0-M9

### ISSUE THREAD

**Issue by kbachl** [wicketstuff/core#626]
reason is the usage of wicket15-tree that has problem with tree opening, see:

StandardWrapperValve[default]: Servlet.service() for servlet default threw exception
java.lang.NoSuchMethodError: org.apache.wicket.extensions.markup.html.tree.AbstractTree$TreeItem.prepareForRender()V
	at org.apache.wicket.extensions.markup.html.tree.AbstractTree$TreeItem$4.visitItem(AbstractTree.java:351)
	at org.apache.wicket.extensions.markup.html.tree.AbstractTree.visitItemAndChildren(AbstractTree.java:1717)
	at org.apache.wicket.extensions.markup.html.tree.AbstractTree.visitItemChildren(AbstractTree.java:1735)....

where line 351 is item.prepareForRender();

**Comment by svenmeier** [comment]
There are several adjustments to be done, I'm working on it.
