### ISSUE TITLE
NullPointerException throws when managing dashboard in multiple tabs on same browser

### ISSUE THREAD

**Issue by madasamys** [wicketstuff/core#654]
**What was Activity?**
1. Run dashboard examples using below command
`mvn clean package jetty:run`
2. Open browser (Using Firefox v65.0.1) and access app `localhost:8081`
3. Open new tab on same browser and access app `localhost:8081`
4. Go to first tab click on _Add widget_ link
5. Go to second tab click on _Add widget_ link
6. And Click on _Add widget_ under **HighChart** category
7. Go to first tab and click on on _Add widget_ under **HighChart** category

**What was observed ?**
Below exception throws
`Root cause:
java.lang.NullPointerException
     at org.wicketstuff.dashboard.examples.AddWidgetPanel$WidgetDescriptorPanel$2.onClick(AddWidgetPanel.java:126)
     at org.apache.wicket.ajax.markup.html.AjaxLink$1.onEvent(AjaxLink.java:85)
     at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:127)
     at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:598)
     at org.apache.wicket.core.request.handler.ListenerRequestHandler.internalInvoke(ListenerRequestHandler.java:306)
     at org.apache.wicket.core.request.handler.ListenerRequestHandler.invoke(ListenerRequestHandler.java:280)
     at org.apache.wicket.core.request.handler.ListenerRequestHandler.invokeListener(ListenerRequestHandler.java:222)
     at org.apache.wicket.core.request.handler.ListenerRequestHandler.respond(ListenerRequestHandler.java:208)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:914)
     at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:65)
     at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:282)
     at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:253)
     at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:221)
     at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:275)
     at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:206)
     at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:299)`

**Expectation**
Exception should not throw when access application in multiple tabs

**Note**
Is this expected behavior in wicket dashboard?

**Comment by solomax** [comment]
Will try to check ASAP
@madasamys  what branch are you using?

**Comment by madasamys** [comment]
@solomax , I am using master branch

**Comment by solomax** [comment]
reproducible using 8.x as well
will try to investigate/fix ASAP
Thanks for detailed steps!

**Comment by madasamys** [comment]
@solomax Thankyou very much for quick fix

**Comment by solomax** [comment]
Thanks again for the detailed steps :)
We also using this module, NPE need to be fixed ASAP :)
